displayName=Wilderness Loadouts
author=DenisSa
support=https://github.com/DenisSa/wilderness-loadouts
description=Find the best defensive Wilderness loadout from equipment you own, within the risk you're willing to take
tags=wilderness,pvp,gear,defence,defense,bank,loadout
version=
plugins=com.denissa.wildernessloadouts.WildernessLoadoutsPlugin
build=standard
