/*
 * Copyright (c) 2026, DenisSa
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.denissa.wildernessloadouts;

import net.runelite.api.gameval.ItemID;

/**
 * Generated by scripts/generate_replacement_values.py. Do not edit manually.
 * RuneLite revision: c3ff99becc8e9e4c1fbd18a9e705cb99df6ee9f7
 * Source data SHA-256: 1d20c824aade8186b9e7d27c65da2ac0ebc689bd4b32da2f3aee4ad20a24a9c7
 */
final class ExactReplacementValues
{
	private ExactReplacementValues()
	{
	}

	static LossProfile get(int itemId)
	{
		switch (itemId)
		{
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_1:
				return LossProfile.exact(
					65L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_10:
				return LossProfile.exact(
					130_000L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_2:
				return LossProfile.exact(
					130L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_3:
				return LossProfile.exact(
					325L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_4:
				return LossProfile.exact(
					650L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_5:
				return LossProfile.exact(
					1_300L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_6:
				return LossProfile.exact(
					1_950L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_7:
				return LossProfile.exact(
					3_250L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_8:
				return LossProfile.exact(
					6_500L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.HUNDRED_GAUNTLETS_LEVEL_9:
				return LossProfile.exact(
					130_000L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Culinaromancer's Chest");
			case ItemID.LUMBRIDGE_RING_EASY:
				return LossProfile.exact(
					200L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUMBRIDGE_RING_ELITE:
				return LossProfile.exact(
					200L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUMBRIDGE_RING_HARD:
				return LossProfile.exact(
					200L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUMBRIDGE_RING_MEDIUM:
				return LossProfile.exact(
					200L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_AMULET:
				return LossProfile.exact(
					9_000L,
					9_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_BOOTS:
				return LossProfile.exact(
					15_000L,
					15_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_CAPE:
				return LossProfile.exact(
					18_000L,
					18_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_GLOVES:
				return LossProfile.exact(
					15_000L,
					15_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_HELMET:
				return LossProfile.exact(
					22_000L,
					22_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_LEGS:
				return LossProfile.exact(
					95_000L,
					95_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_MOONCLAN_LIMINAL_STAFF:
				return LossProfile.exact(
					60_000L,
					60_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_RING:
				return LossProfile.exact(
					8_000L,
					8_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.LUNAR_TORSO:
				return LossProfile.exact(
					140_000L,
					140_000L,
					false,
					LossProfile.ReacquisitionMethod.PERDU,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Lost Property shop");
			case ItemID.MYTHICAL_CAPE:
				return LossProfile.exact(
					10_000L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.QUEST_SHOP,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Mythical cape");
			case ItemID.RING_OF_SHADOWS:
				return LossProfile.exact(
					75_000L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.NPC_REPLACEMENT,
					LossProfile.NonMonetaryBurden.CHARGES,
					"OSRS Wiki: Ring of shadows");
			case ItemID.RING_OF_SHADOWS_UNCHARGED:
				return LossProfile.exact(
					75_000L,
					0L,
					true,
					LossProfile.ReacquisitionMethod.NPC_REPLACEMENT,
					LossProfile.NonMonetaryBurden.NONE,
					"OSRS Wiki: Ring of shadows");
			default:
				return null;
		}
	}
}
